name: Scheduled health check
on:
  schedule:
    - cron: "* * * * *"

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://pokedex-stuge.herokuapp.com/health
